---
# Install dependencies for building linux on Debian

- name: Allow for distro source change / upgrade
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  command: "apt-get update  --allow-releaseinfo-change"
  args:
    warn: no
  tags: [ 'linux', 'deps' ]

- name: Update apt cache
  become: yes
  become_method: sudo
  apt:
    update_cache: yes
  tags: linux

# apt-get build-dep does not capture all requirements
- name: Install Linux kernel build dependencies
  become: yes
  become_method: sudo
  apt:
    name:
      - bison
      - flex
      - git
      - gcc
      - make
      - gawk
      - bc
      - dump
      - indent
      - sed
      - libssl-dev
      - libelf-dev
      - xfsprogs
    state: present
  tags: linux
