---
# Distro specific
- include: tasks/install-deps/main.yml

# Distro agnostic stuff to build and boot Linux goes below

- name: git clone {{ target_linux_tree }}
  git:
    repo: "{{ target_linux_git }}"
    dest: "{{ target_linux_dir_path }}"
    update: yes
    version: "{{ target_linux_tag }}"
  tags: [ 'linux', 'git', 'clone']

- name: Copy configuration for linux {{ target_linux_tree }}
  template:
    src: "{{ target_linux_config }}"
    dest: "{{ target_linux_dir_path }}/.config"
    owner: "{{ data_user }}"
    group: "{{ data_group }}"
    mode: 0644
  tags: [ 'linux', 'config' ]

- name: Configure linux {{ target_linux_tree }}
  shell: yes "" | make oldconfig
  args:
    chdir: "{{ target_linux_dir_path }}"
  tags: [ 'linux', 'oldconfig' ]

- name: Build linux {{ target_linux_tree }}
  command: "{{ target_linux_make_cmd }}"
  args:
    chdir: "{{ target_linux_dir_path }}"
  tags: [ 'linux', 'build-linux' ]

- name: Install linux {{ target_linux_tree }}
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  command: "{{ target_linux_make_install_cmd }}"
  args:
    chdir: "{{ target_linux_dir_path }}"
  tags: linux
  tags: [ 'linux', 'install-linux' ]

- name: Reboot into linux {{ target_linux_tree }}
  become: yes
  become_method: sudo
  reboot:
  tags: [ 'linux', 'reboot' ]
