# http://docs.ansible.com/galaxy.html#installing-multiple-roles-from-a-file
# The skinny: ansible-galaxy install -r requirements.yml

- src: mcgrof.kdevops_install
  name: mcgrof.kdevops_install
  version: v1.9.5
