# http://docs.ansible.com/galaxy.html#installing-multiple-roles-from-a-file
# The skinny: ansible-galaxy install -r requirements.yml

- src: mcgrof.install_terraform
  name: mcgrof.install_terraform
  version: v0.0.4

- src: mcgrof.install_vagrant
  name: mcgrof.install_vagrant
  version: v0.2.7

- src: mcgrof.libvirt_user
  name: mcgrof.libvirt_user
  version: v0.0.10

- src: mcgrof.kdevops_vagrant
  name: mcgrof.kdevops_vagrant
  version: v1.1.1

- src: mcgrof.kdevops_terraform
  name: mcgrof.kdevops_terraform
  version: v0.6.6

- src: mcgrof.create_partition
  name: mcgrof.create_partition
  version: v1.2.0

- src: mcgrof.update_ssh_config_vagrant
  name: mcgrof.update_ssh_config_vagrant
  version: v1.2.1

- src: mcgrof.devconfig
  name: mcgrof.devconfig
  version: v1.2.1

- src: mcgrof.bootlinux
  name: mcgrof.bootlinux
  version: v1.3.6

- src: mcgrof.fix_dhcp_hack
  name: mcgrof.fix_dhcp_hack
  version: v0.0.8
