# http://docs.ansible.com/galaxy.html#installing-multiple-roles-from-a-file
# The skinny: ansible-galaxy install -r requirements.yml

- src: mcgrof.kdevops_vagrant
  name: mcgrof.kdevops_vagrant
  version: v1.0.1

- src: mcgrof.kdevops_terraform
  name: mcgrof.kdevops_terraform
  version: v0.3.0

- src: mcgrof.create_partition
  name: mcgrof.create_partition
  version: v1.2.0

- src: mcgrof.update_ssh_config_vagrant
  name: mcgrof.update_ssh_config_vagrant
  version: v1.2.0

- src: mcgrof.devconfig
  name: mcgrof.devconfig
  version: v1.0.2

- src: mcgrof.bootlinux
  name: mcgrof.bootlinux
  version: v1.3.0
