# SPDX-License-Identifier GPL-2.0+ OR MIT
---
# tasks file for configuring the watchdog - whiskerlabs.watchdog
- name: configure watchdog daemon
  become: yes
  become_method: sudo
  template:
    src: watchdog.conf.j2
    dest: /etc/watchdog.conf
  tags: [ 'watchdog', 'config' ]

- name: Restart watchdog
  become: yes
  become_flags: 'su - -c'
  become_method: sudo
  ignore_errors: yes
  tags: [ 'watchdog', 'config' ]
  service:
    name: watchdog
    state: restarted
